{application,ibrowse,
             [{description,"Erlang HTTP client application"},
              {vsn,"4.0.1"},
              {registered,[ibrowse_sup,ibrowse]},
              {applications,[kernel,stdlib]},
              {env,[]},
              {mod,{ibrowse_app,[]}},
              {modules,[db,ecrawler_app,ecrawler_sup,emysql,emysql_app,
                        emysql_auth,emysql_conn,emysql_conn_mgr,
                        emysql_statements,emysql_sup,emysql_tcp,emysql_tracer,
                        emysql_util,emysql_worker,httpclient,ibrowse,
                        ibrowse_app,ibrowse_http_client,ibrowse_lb,
                        ibrowse_lib,ibrowse_sup]}]}.
