{application,ecrawler,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{ecrawler_app,[]}},
              {env,[]},
              {modules,[db,ecrawler_app,ecrawler_sup,erl_http_client,
                        httpclient]}]}.
